language: python
sudo: false
python:
  - '3.6.5'

install:
  - pip install -r requirements/common.txt
  - pip install flake8

script:
  - flake8

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
