language: python
sudo: false
python:
  - '3.7.3'

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/common.txt
  - pip install codecov

script:
  - flake8
  - pytest --cov -v --tb=native

after_success:
  - codecov

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
