# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-20 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(verbose_name='Facebook Page Name')),
                ('access_token', models.TextField(verbose_name='Facebook Page Access Token')),
                ('page_id', models.TextField(verbose_name='Facebook Page ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Facebook Page Owner')),
            ],
            options={
                'db_table': 'facebookpages',
                'verbose_name_plural': 'Facebook Pages',
                'verbose_name': 'Facebook Page',
            },
        ),
        migrations.CreateModel(
            name='MessengerLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.TextField(verbose_name='Messenger Label Name')),
                ('label_id', models.TextField(verbose_name='Messenger Label Id')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Messenger Label Owner')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookPage', verbose_name='Facebook Page')),
            ],
            options={
                'db_table': 'messengerlabels',
                'verbose_name_plural': 'Messenger Labels',
                'verbose_name': 'Messenger Label',
            },
        ),
        migrations.CreateModel(
            name='PSIDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid_list', models.TextField(verbose_name='PSID List')),
                ('valid_psid', models.TextField(blank=True, default=None, null=True, verbose_name='Valid PSID List')),
                ('invalid_psid', models.TextField(blank=True, default=None, null=True, verbose_name='Invalid PSID List')),
                ('label_associated_to', models.TextField(blank=True, default=None, null=True, verbose_name='Label Associated To')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.MessengerLabel', verbose_name='Messenger Label')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookPage', verbose_name='Facebook Page')),
            ],
            options={
                'db_table': 'psidlists',
                'verbose_name_plural': 'PSID Lists',
                'verbose_name': 'PSID List',
            },
        ),
    ]
