# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psidlist',
            name='psid_list',
            field=models.FileField(blank=False, null=False, upload_to='./debug', verbose_name='PSID List'),
        ),
    ]
